services:
  # 1. Base de Datos (MySQL)
  db:
    image: mysql:8.0
    container_name: db-pasteleria
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pasteleria
    volumes:
      - ./PasteleriaScript.sql:/docker-entrypoint-initdb.d/setup.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "3306:3306"

  # 2. Backend (Spring Boot)
  backend:
    build: ./Pasteleria/Pasteleria
    container_name: backend-pasteleria
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/pasteleria?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      db:
        condition: service_healthy

  # 3. Servidor Web y Proxy (Nginx)
  nginx:
    image: nginx:latest
    container_name: nginx-pasteleria
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Front/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - backend